# Generated by Django 4.1.6 on 2023-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image4",
            field=models.ImageField(blank=True, upload_to="store/products/"),
        ),
    ]
