# Generated by Django 4.1.6 on 2023-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_products_image4"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="noofitems",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
