# Generated by Django 4.1.6 on 2023-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
