# Generated by Django 4.1.6 on 2023-05-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="productid",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="userid",
            new_name="user",
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="cart",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.cart"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="orderstatus",
            field=models.CharField(default="pending", max_length=200),
        ),
    ]
