# Generated by Django 4.1.6 on 2023-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_productid_orders_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="cart",
        ),
        migrations.AddField(
            model_name="orders",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
