# Generated by Django 4.1.6 on 2023-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_orders_cart_orders_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="ordertype",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
