# Generated by Django 4.1.6 on 2023-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_orders_ordertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="store/categorys/"),
        ),
    ]
