# Generated by Django 4.1.6 on 2023-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="isblocked",
            field=models.BooleanField(default=False),
        ),
    ]
