# Generated by Django 4.1.6 on 2023-05-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_category_isblocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
