# Generated by Django 4.1.6 on 2023-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_products_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200, unique=True)),
                ("discount", models.CharField(max_length=200)),
                ("minprice", models.PositiveIntegerField()),
                ("maxprice", models.PositiveIntegerField()),
                ("isavailable", models.BooleanField(default=True)),
            ],
        ),
    ]
