# Generated by Django 4.1.6 on 2023-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="discount",
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_percentage",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
