# Generated by Django 4.1.6 on 2023-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_coupon_discount_coupon_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="offer1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="offer2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="offer3",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
