# Generated by Django 4.1.6 on 2023-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_categoryoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="finalprice",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
