# Generated by Django 4.1.6 on 2023-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_orders_finalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="finalprice",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
