# Generated by Django 4.1.6 on 2023-06-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordernumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slno", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="slno",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.ordernumber",
            ),
            preserve_default=False,
        ),
    ]
