# Generated by Django 4.1.6 on 2023-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_ordernumber_orders_slno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="slno",
            new_name="ordernumber",
        ),
        migrations.AddField(
            model_name="ordernumber",
            name="totalamount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
