# Generated by Django 4.1.6 on 2023-06-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_ordernumber_coupon_ordernumber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordernumber",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.coupon",
            ),
        ),
    ]
